### ISSUE TITLE
Using bidirectional encoder and attentional GRUs

### ISSUE THREAD

**Issue by eonu** [Maghoumi/DeepGRU#2]
Hi, I've recently been working on making an implementation of DeepGRU in PyTorch, and I was wondering if there is any particular reason why any of the encoder network layers and even the attentional GRU are not bidirectional. 

Is it for computational cost reasons? Or is it something that you experimented with that led to no improvement in recognition accuracy?

**Comment by Maghoumi** [comment]
Hi,

We experimented with bidirectional RNNs as well. As you pointed out, computational cost was noticeably higher and we didn't observe any significant benefits in using such units. Thus we decided to use unidirectional units thereafter.

**Comment by eonu** [comment]
Makes sense, thanks for the quick response!
